type: app
description: Default stackfile usecase description
# template used to create the project
template: gitbuh/estrutura-template
inputs:
  some_input: value
# list of plugins to be applied after project creation
plugins:
  - plugin: gitbuh/configured_ambiente
    inputs:
      some_input: value
      some_list:
        - item1
        - item2
